name: Build & Release

on: [workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          bash scripts/prep.gomod.sh
          export WORK_FOLDER=/__/work/${GITHUB_RUN_NUMBER}
          mkdir -p $WORK_FOLDER
          cp -r . $WORK_FOLDER/sling
          docker run --rm -v /__/docker-data/devbox/root/go:/root/go -v /__:/__ -v /tmp:/tmp -v $WORK_FOLDER:/work --workdir /work/sling flarco/devbox:base bash scripts/build.linux.sh
          rm -rf $WORK_FOLDER

  push:
    needs: [build]
    runs-on: self-hosted

    steps:
      - name: Push Docker
        run: |
          /bin/cp /tmp/sling-linux ./sling

          VERSION=$(./sling --version | sed 's/Version: //')

          source /__/devbox/.env.sh
          export _DEBUG=''
          echo "$DOCKER_PASSWORD" | docker login -u flarco --password-stdin

          docker build -t flarco/sling:$VERSION -f cmd/sling/Dockerfile .
          docker tag flarco/sling:$VERSION flarco/sling:latest
          docker push flarco/sling:$VERSION
          docker push flarco/sling:latest
          docker image rm -f flarco/sling:$VERSION

  release:
    needs: [build]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Dump context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: |
          echo "JOB_CONTEXT -> $JOB_CONTEXT"
          echo "MATRIX_CONTEXT -> $MATRIX_CONTEXT"
          echo "RUNNER_CONTEXT -> $RUNNER_CONTEXT"

      - name: Set up GoLang
        uses: actions/setup-go@v1
        with:
          go-version: "1.18"

      - name: Prepare Build (Unix)
        if: runner.os != 'windows'
        run: |
          export GO_BIN_FOLDER=$HOME/go/bin
          export TMPDIR=~/tmp/
          export PATH=$GO_BIN_FOLDER:$PATH
          mkdir -p $TMPDIR

      - name: Prepare Build (Windows)
        if: runner.os == 'windows'
        run: |
          setx TMPDIR "C:\Users\runneradmin\tmp"
          setx PATH "%PATH%;C:\Users\runneradmin\go\bin"
          setx GO111MODULE "auto"
          mkdir C:\Users\runneradmin\tmp

      - name: Build Sling (Linux)
        if: runner.os == 'linux'
        run: |
          echo "Building sling-linux"
          bash scripts/prep.gomod.sh
          GOOS=linux GOARCH=amd64 go build -o sling-linux cmd/sling/*.go

      - name: Build Sling (Mac)
        if: runner.os == 'macOS'
        run: |
          echo "Building sling-mac"
          bash scripts/prep.gomod.sh
          GOOS=darwin GOARCH=amd64 go build -o sling-mac cmd/sling/*.go

      - name: Build Sling (Windows)
        if: runner.os == 'windows'
        run: |
          echo "Building sling-win.exe"
          setx GOOS "windows"
          setx GOARCH "386"
          setx GO111MODULE "auto"

          go mod edit -dropreplace='github.com/flarco/g' go.mod
          go mod edit -dropreplace='github.com/flarco/dbio' go.mod
          go get github.com/flarco/g@HEAD
          go get github.com/flarco/dbio@HEAD

          go build -o sling-win.exe github.com/flarco/sling/cmd/sling

      - name: Release Binaries to Github
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-${{ runner.os }}"
          prerelease: true
          title: "Latest: ${{ runner.os }}"
          files: |
            sling*
      
      - uses: actions/upload-artifact@v2
        with:
          name: sling-dist
          path: sling*

  release-python:
    needs: [release]
    runs-on: self-hosted

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      - uses: actions/download-artifact@v2
        with:
          name: sling-dist
      
      - name: Upload to PyPi
        run: |
          source /__/devbox/.env.sh
          mkdir python/sling/bin/

          mv -f sling-mac python/sling/bin/
          mv -f sling-linux python/sling/bin/
          mv -f sling-win.exe python/sling/bin/
          chmod -R 755 python/sling/bin/

          cd python
          pip install -e .
          pip install twine
          python setup.py sdist && twine upload --verbose --skip-existing dist/*