name: Bump version
on:
  workflow_call:
    outputs:
      new_tag:
        description: "The new tag"
        value: ${{ jobs.bump.outputs.new_tag }}
  
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag: x.x.x'     
        required: true
jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ github.event.inputs.tag }}
  
  # build-test:
  #   needs: [bump]
  #   runs-on: ubuntu-latest

  #   steps:          
  #     - name: Trigger Build & Test
  #       uses: peter-evans/repository-dispatch@v2
  #       with:
  #         token: ${{ secrets.REPO_ACCESS_TOKEN }}
  #         repository: slingdata-io/sling-cli
  #         event-type: build-test
  #         client-payload: "{\"version\": \"${{ needs.bump.outputs.new_tag }}\"}"