name: Test Version

on: [workflow_dispatch]

jobs:
  test1:
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v2
        
      - name: Get the version
        id: get_version
        run: |
          TAG=$(git tag -l --sort=-creatordate | head -n 1)
          VERSION=$(echo $TAG | sed 's/v//')
          echo ::set-output name=version::$VERSION
          
      - name: Get the version
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          echo "VERSION -> $VERSION"
          echo "TAG2 -> $(git tag -l --sort=-creatordate | head -n 1)"

  test-mac:
    runs-on: [self-hosted, macOS, ARM64]
    timeout-minutes: 20

    steps:
      # - name: Git Fetch (to fix (would clobber existing tag)
      #   run: git fetch --tags --force
          
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

  test-windows:
    # runs-on: [self-hosted, Windows]
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

  test-linux-arm64:
    runs-on: [self-hosted, Linux, ARM64]
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

  test-linux-amd64:
    # runs-on: ubuntu-20.04
    runs-on: [self-hosted, Linux, X64, ubuntu-16]
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
  