name: Test Version

on: [workflow_dispatch]

jobs:
  test1:
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v2
        
      - name: Get the version
        id: get_version
        run: |
          TAG=$(git tag -l --sort=-creatordate | head -n 1)
          VERSION=$(echo $TAG | sed 's/v//')
          echo ::set-output name=version::$VERSION
          
      - name: Get the version
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          echo "VERSION -> $VERSION"
          echo "TAG2 -> $(git tag -l --sort=-creatordate | head -n 1)"