name: Test Version

on: [workflow_dispatch]

jobs:
  test1:
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v2
        
      - name: Get the version
        env:
          TAG: ${{ steps.get-latest-tag.outputs.tag }}
        run: |
          echo "VERSION -> $VERSION"
          echo "REF_NAME -> $REF_NAME"
          echo "TAG1 -> $(git describe --tags --abbrev=0)"
          echo "TAG2 -> $(git tag -l --sort=-creatordate | head -n 1)"